import { Boss } from "@/types";

export const bosses: Boss[] = [
  // ==================== 四季Boss ====================
  {
    id: "deerclops",
    name: "巨鹿", nameEn: "Deerclops",
    season: "winter", location: "冬季第30天左右在地表生成，会主动寻找玩家并摧毁建筑",
    health: 4000, damage: 75,
    attackPattern: ["近战拍击(75伤害，对玩家)", "范围冰冻攻击(对生物和建筑双倍伤害，150伤害)"],
    drops: [
      { itemName: "肉", quantity: "8块", dropRate: "always" },
      { itemName: "巨鹿眼球", quantity: "1个", dropRate: "always" },
      { itemName: "巨鹿雕塑蓝图", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "冬季夜晚在地表生成。会优先寻找建筑进行破坏。靠近时会听到明显的喘息声。",
    kitingPattern: "打2走1（攻击两次后躲避），注意范围冰冻攻击的前摇", minPlayersRecommended: 1,
    imagePath: "/images/bosses/deerclops.png",
    description: "巨鹿是冬季Boss，拥有强大的AOE冰冻攻击。它的眼球可以制作眼球伞（100%防雨+240隔热），是春夏季节必备装备。",
    strategy: "1. 提前准备木甲+猪皮头盔（减免80%+80%=96%伤害），每次被击中只受约3点伤害\n2. 巨鹿的冰冻攻击对生物造成双倍伤害，不要带随从\n3. 带两根暖石保持体温\n4. 如果打不过，可以引导巨鹿去砍树——它会召唤树精，让它们打起来\n5. 最佳方案：拉到沼泽让触手帮忙输出\n6. 走位：打2下后后退两步躲避，注意听声音预判攻击",
  },
  {
    id: "bearger",
    name: "熊獾", nameEn: "Bearger",
    season: "autumn", location: "秋季第2年左右生成，会偷吃地上的食物和农作物",
    health: 6000, damage: 100,
    attackPattern: ["近战拍击(100伤害)", "冲刺攻击", "坐下产生冲击波(破坏周围建筑和树木)"],
    drops: [
      { itemName: "肉", quantity: "8块", dropRate: "always" },
      { itemName: "熊皮", quantity: "1张", dropRate: "always" },
      { itemName: "熊獾雕塑蓝图", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "秋季在地表生成。会偷吃地上的食物（包括农田和晾肉架上的食物）。吃够一定数量后进入冬眠。",
    kitingPattern: "打2走1（普通攻击），注意冲刺攻击需要侧向躲避", minPlayersRecommended: 1,
    imagePath: "/images/bosses/bearger.png",
    description: "熊獾是秋季Boss，血量6000攻击力高。但它有一个特性：可以帮你砍树。熊皮可以制作隔热背包和熊皮背心，是冬季保暖核心装备。",
    strategy: "1. 利用熊獾砍树：引导它冲刺撞树，一次可以砍倒大片森林，还会震出树精\n2. 带去沼泽让触手帮忙输出\n3. 带足够的武器（约3-4把火腿棒或长矛）\n4. 注意别让它在基地附近坐下，会摧毁建筑\n5. 如果不想打，让它吃够食物后会冬眠，此时可以安全地捡取掉落物\n6. 如果引去沼泽，触手会持续输出，你只需补刀",
  },
  {
    id: "moose-goose",
    name: "麋鹿鹅", nameEn: "Moose/Goose",
    season: "spring", location: "春季在地表随机生成（通常在草原/森林交界处）",
    health: 6000, damage: 75,
    attackPattern: ["近战啄击(75伤害)", "震地冲击(范围击退)", "召唤小鹅（春天雷雨时蛋孵化出5只小鹅）"],
    drops: [
      { itemName: "肉", quantity: "6块", dropRate: "always" },
      { itemName: "鸡腿", quantity: "3-5个", dropRate: "always" },
      { itemName: "羽绒", quantity: "6-10根", dropRate: "always" },
      { itemName: "麋鹿鹅雕塑蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "天气风向标蓝图", quantity: "1个", dropRate: "rare" },
    ],
    spawnConditions: "春季在地表随机位置生成，通常伴随一个巨大的蛋。蛋在雷雨天会孵化出小鹅。",
    kitingPattern: "打3走1——攻击较慢，走位简单。注意震地范围。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/moose-goose.png",
    description: "麋鹿鹅是春季Boss，本体难度不高但小鹅群很烦。羽绒是制作天气风向标（范围旋风武器）和羽毛扇（夏季降温神器）的核心材料。",
    strategy: "1. 先杀小鹅再打本体，避免被围殴\n2. 本体走位简单——打3下走1步即可\n3. 天气风向标是清理大量小型怪物的神器\n4. 羽毛扇是夏季必备（降温+灭火）\n5. 不要在蛋旁边建家——春天会突然孵出一群小鹅",
  },
  {
    id: "dragonfly",
    name: "龙蝇", nameEn: "Dragonfly",
    season: "summer", location: "沙漠地带（固定位置），有专属的岩浆池巢穴",
    health: 27500, damage: 75,
    attackPattern: ["近战拍击(75伤害)", "火焰吐息(三连击，AOE伤害)", "召唤岩浆虫(最多20只)", "暴怒状态（攻击和移速大幅提升）"],
    drops: [
      { itemName: "鳞片", quantity: "1片", dropRate: "always" },
      { itemName: "各色宝石", quantity: "红蓝紫各1-2个", dropRate: "always" },
      { itemName: "金块", quantity: "8块", dropRate: "always" },
    ],
    spawnConditions: "夏季在沙漠龙蝇巢穴生成。不会主动离开沙漠。每20秒检查一次是否被孤立（如果周围无岩浆虫则暴怒）。",
    kitingPattern: "打2-3走1，注意躲避三连火焰吐息", minPlayersRecommended: 2,
    imagePath: "/images/bosses/dragonfly.png",
    description: "龙蝇是夏季Boss，地表血量最高的Boss之一（27500血）。鳞片可以制作鳞甲（防火甲）和鳞片箱（防火储物箱），非常珍贵。",
    strategy: "1. 建造石墙将岩浆池围起来，防止龙蝇回血\n2. 准备消暑装备：冰帽/眼球伞+冰块\n3. 龙蝇暴怒时伤害极高，需要用冰杖或冰块灭火来安抚\n4. 团队打法：一人拉仇恨，其他人输出\n5. 鳞甲是防火装备，适合在洞穴中对抗火焰攻击\n6. 准备20+防具和大量武器，这是持久战",
  },
  {
    id: "antlion",
    name: "蚁狮", nameEn: "Antlion",
    season: "summer", location: "绿洲沙漠（固定位置），地表有陨石坑标记",
    health: 6000, damage: 50,
    attackPattern: ["召唤沙刺(从地面突刺)", "召唤沙堡(阻挡移动)", "流星撞击(AOE伤害)"],
    drops: [
      { itemName: "沙漠石头", quantity: "6-8个", dropRate: "always" },
      { itemName: "绿洲堡垒蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "懒惰的探险家蓝图", quantity: "1个", dropRate: "rare" },
    ],
    spawnConditions: "夏季在绿洲沙漠固定位置生成。如果不定期用暖石或岩石进贡，它会随机在玩家所在位置制造陨石坑（造成伤害+破坏建筑）。",
    kitingPattern: "远程角色优势较大。近战需要绕过沙堡输出。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/antlion.png",
    description: "蚁狮是夏季地下的另一个Boss。如果不定期进贡（给它暖石或岩石），它会在你的基地随机召唤陨石。击败后掉落懒惰的探险家蓝图——可以制作权杖进行短距离传送，神器级别。",
    strategy: "1. 冰杖冻住后输出是最简单的方法\n2. 如果不打，每几天给它一块岩石/暖石即可安抚\n3. 懒惰的探险家权杖可以瞬间移动到鼠标位置——跑图神器\n4. 沙刺攻击有明显的地面提示，注意躲避\n5. 带眼球伞+冰块防止夏季过热",
  },
  // ==================== 洞穴/遗迹Boss ====================
  {
    id: "ancient-guardian",
    name: "远古守卫者", nameEn: "Ancient Guardian",
    season: "any", location: "洞穴迷宫最深处（固定位置）",
    health: 10000, damage: 100,
    attackPattern: ["冲锋撞击(100伤害，撞到障碍物会晕眩)", "近战扫击"],
    drops: [
      { itemName: "肉", quantity: "8块", dropRate: "always" },
      { itemName: "守护者之角", quantity: "1个", dropRate: "always" },
      { itemName: "大型华丽箱子", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "固定位于洞穴迷宫最深处。需要先穿过迷宫区域才能到达。",
    kitingPattern: "利用柱子卡冲锋——引它撞墙后晕眩，趁机疯狂输出。无限循环。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/ancient-guardian.png",
    description: "远古守卫者是洞穴迷宫的守护者，最经典的机制型Boss。冲锋撞到障碍物后会晕眩，玩家可趁机输出。守护者之角可以制作Houndius Shootius（自动防御炮塔），是基地防御的核心。",
    strategy: "1. 站在柱子后面等它冲锋——撞墙后晕眩疯狂输出\n2. 循环柱子打法几乎无伤\n3. 守护者之角+鹿角+眼球=自动炮塔\n4. 迷宫需要带足够光源和食物\n5. 击杀后迷宫箱子中有大量远古装备",
  },
  {
    id: "toadstool",
    name: "毒菌蟾蜍", nameEn: "Toadstool",
    season: "any", location: "洞穴中的毒菌池（找到三片池塘中的毒菌环即可召唤）",
    health: 52500, damage: 100,
    attackPattern: ["近战撞击(100伤害)", "跳跃压顶", "蘑菇云(AOE伤害+孢子树)", "召唤孢子树（需要砍掉否则它会变强）"],
    drops: [
      { itemName: "毒菌皮", quantity: "1-3张", dropRate: "always" },
      { itemName: "蘑菇灯蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "休眠阶段掉落物", quantity: "见说明", dropRate: "always" },
    ],
    spawnConditions: "在三个毒菌池中找到毒菌环，用斧头砍三次后召唤。需要使用锤子/斧头清除孢子树，否则它会不断强化。",
    kitingPattern: "时刻关注孢子树——必须优先砍掉。跳跃压顶有明显的落地提示。", minPlayersRecommended: 3,
    imagePath: "/images/bosses/toadstool.png",
    description: "毒菌蟾蜍是游戏中血量最高的Boss之一（52500血）。需要在它召唤孢子树时迅速砍掉，否则Boss会不断升级。毒菌皮可以制作蘑菇灯（永久照明，不用加燃料！）。" + (""),
    strategy: "1. 至少3人团队——2人砍孢子树+1人拉仇恨\n2. 使用斧头和锤子（金斧/玻璃斧更快）\n3. 蘑菇灯是永久照明——不需要加燃料，建家神器\n4. 带足够武器：血量太高，至少要6-8把武器\n5. 如果单人打，温蒂的阿比盖尔可以帮忙砍孢子树",
  },
  {
    id: "ancient-fuelweaver",
    name: "远古编织者", nameEn: "Ancient Fuelweaver",
    season: "any", location: "洞穴中庭（Atrium），收集骨架+暗影之心召唤",
    health: 16000, damage: 100,
    healthNote: "（有多个阶段和护盾机制）",
    attackPattern: ["近战攻击(100伤害)", "召唤暗影触手(牢笼困住玩家)", "吃暗影生物回血(每秒400！)", "暗影光环(理智快速下降)", "第二阶段：狂暴模式"],
    drops: [
      { itemName: "骨甲", quantity: "1个", dropRate: "always" },
      { itemName: "骨盔", quantity: "1个", dropRate: "always" },
      { itemName: "暗影图斯雕像蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "重置洞穴的暗影心脏", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "在洞穴中庭（Atrium）使用化石碎片+暗影心脏在远古入口处召唤。需要先获得暗影心脏（击杀暗影三兄弟后获得）。",
    kitingPattern: "极其复杂——需要同时应对本体、暗影触手、牢笼、暗影生物", minPlayersRecommended: 2,
    imagePath: "/images/bosses/ancient-fuelweaver.png",
    description: "远古编织者是游戏的最终Boss之一——极其复杂的战斗机制：需要管理暗影触手牢笼、阻止它吃暗影生物回血（每秒回400！）、应对快速下降的理智。但战利品无与伦比：骨甲（无敌护盾）和骨盔（80%减伤），是最强防具。",
    strategy: "1. 必须阻止它吃暗影生物——用回旋镖/远程武器击杀\n2. 暗影触手会用骨笼困住你——队友可以打破笼子\n3. 骨甲的无敌护盾可以抵挡任何伤害——战斗中冷却好了就用\n4. WEATHER PAIN（天气风向标）在这个Boss战中极其好用\n5. 蜜蜂帽/蜂后冠可以降低理智损失\n6. 建议2-3人团队——这是全游戏最难的单体Boss",
  },
  {
    id: "nightmare-werepig",
    name: "梦魇猪人", nameEn: "Nightmare Werepig",
    season: "any", location: "洞穴的猪人墓地（使用镐子敲开堵住的洞口）",
    health: 10000, damage: 120,
    attackPattern: ["三连击(每击120伤害，可格挡)", "冲锋撞击", "跳砸AOE"],
    drops: [
      { itemName: "暗影肉", quantity: "4-6块", dropRate: "always" },
      { itemName: "纯粹恐惧", quantity: "3-5个", dropRate: "always" },
      { itemName: "梦魇燃料", quantity: "2-4个", dropRate: "always" },
    ],
    spawnConditions: "在洞穴地下找到一个被堵住的猪人墓地入口，用镐子砸开后触发。",
    kitingPattern: "三连击有明显的蓄力动作——侧向躲避。冲锋后可以反击。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/nightmare-werepig.png",
    description: "梦魇猪人是洞穴中的一个强力Boss，攻击力极高（120伤害）。掉落纯粹恐惧——这是制作恐惧装备（恐惧盔甲、恐惧工具等）的核心材料。",
    strategy: "1. 三连击是最大的威胁——看清动作侧向闪避\n2. 木甲+猪皮头盔是基础——被120伤害打中非常痛\n3. 纯粹恐惧可以制作诸多恐惧系列装备\n4. 单人也是可打的——走位要求较高\n5. 冰杖可以创造输出窗口",
  },
  // ==================== 冬季特殊Boss ====================
  {
    id: "klaus",
    name: "克劳斯", nameEn: "Klaus",
    season: "winter", location: "冬季在落叶林/马赛克地形出现（需要一个鹿角钥匙开启它的袋子）",
    health: 10000, damage: 50,
    healthNote: "（本体5000+冰鹿5000）",
    attackPattern: ["近战拍击(50伤害)", "召唤冰鹿（克劳斯跳到鹿上后技能变化）", "冰弹攻击(冰鹿状态下)", "连续跳跃攻击"],
    drops: [
      { itemName: "克劳斯宝箱", quantity: "1个", dropRate: "always" },
      { itemName: "鹿角", quantity: "1个", dropRate: "always" },
      { itemName: "（宝箱内含大量战利品）", quantity: "多件", dropRate: "always" },
    ],
    spawnConditions: "冬季在落叶林/马赛克混合地形出现。需要用一个鹿角（无眼鹿掉落）打开它的赃物袋才能召唤。",
    kitingPattern: "克劳斯本体走位简单——打2走1。冰鹿状态下需要躲避冰弹。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/klaus.png",
    description: "克劳斯是冬季宝箱Boss——击败后的宝箱是游戏中最好的战利品来源之一。宝箱可能包含曼德拉草、宝石、铥矿装备、各类蓝图等稀有物品。每年冬季可以打一次（使用鹿角召唤）。",
    strategy: "1. 先获取鹿角——在冬季追踪无眼鹿（它会带你找到鹿角）\n2. 先击杀冰鹿再打克劳斯，或者直接输出克劳斯\n3. 宝箱战利品非常丰厚——每年必打\n4. 冰杖可以冻住冰鹿减轻压力\n5. 克劳斯本身伤害不算高——重点是处理双目标",
  },
  // ==================== 海上Boss ====================
  {
    id: "malbatross",
    name: "邪天翁", nameEn: "Malbatross",
    season: "any", location: "海上（需要在特定海域标记鱼群位置钓鱼触发）",
    health: 5000, damage: 100,
    attackPattern: ["俯冲攻击(100伤害)", "翅膀扇风(吹飞玩家/物品)", "召唤波浪(改变船的位置)"],
    drops: [
      { itemName: "邪天翁羽毛", quantity: "3-5根", dropRate: "always" },
      { itemName: "邪天翁喙", quantity: "1个", dropRate: "always" },
      { itemName: "肉", quantity: "6块", dropRate: "always" },
    ],
    spawnConditions: "在海上找到鱼群标记（水面有大量鱼影跳跃），用海钓竿钓鱼时有概率触发。需要坐船进行战斗。",
    kitingPattern: "船上战斗无法走位——注意它俯冲时躲到船的另一端", minPlayersRecommended: 2,
    imagePath: "/images/bosses/malbatross.png",
    description: "邪天翁是海洋Boss——必须在船上战斗。翅膀扇风会吹飞船上的物品甚至玩家。邪天翁羽毛可以制作羽毛帆（最快的船帆），喙可以制作水壶（浇水工具）。",
    strategy: "1. 在船上放置锚——防止被翅膀吹飞太远\n2. 邪天翁俯冲后有几秒的攻击窗口\n3. 带备用船板和船补丁——船可能会被打坏\n4. 羽毛帆是游戏中最快的船帆\n5. 建议两人以上——一人开船一人打",
  },
  {
    id: "crab-king",
    name: "蟹王", nameEn: "Crab King",
    season: "any", location: "海上（固定位置有巨型蟹壳，需要嵌入宝石召唤）",
    health: 20000, damage: 60,
    healthNote: "（取决于嵌入的宝石种类）",
    attackPattern: ["蟹钳攻击(60伤害)", "召唤海浪(破坏船)", "冰冻光环(蓝宝石嵌入时)", "召唤螃蟹士兵"],
    drops: [
      { itemName: "蟹王壳", quantity: "1个", dropRate: "always" },
      { itemName: "三叉戟蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "宝藏（沉入海中）", quantity: "见说明", dropRate: "always" },
    ],
    spawnConditions: "在海上找到巨型蟹壳结构，嵌入宝石（最少1颗，最多8颗）后召唤。不同颜色宝石赋予不同能力。",
    kitingPattern: "全程在船上战斗——使用冰杖控制+蜂雷密集轰炸是最常见打法", minPlayersRecommended: 2,
    imagePath: "/images/bosses/crab-king.png",
    description: "蟹王是海洋Boss——必须在船上战斗。嵌入宝石种类决定它的技能（蓝宝石=冰冻光环，红宝石=火焰攻击，紫宝石=召唤更多螃蟹等）。击败后获得蟹王壳和三叉戟蓝图。",
    strategy: "1. 全嵌珍珠宝石是最佳选择——减少冰冻和召唤\n2. 蜂雷（Killer Bee Mine）是最佳输出方式——大量蜂雷+冰杖\n3. 螃蟹士兵可以用冰杖冻住\n4. 带足够船补丁——海浪伤害很高\n5. 三叉戟是水上远程武器——对付水上的暗影生物很好用",
  },
  // ==================== 其他Boss ====================
  {
    id: "bee-queen",
    name: "蜂后", nameEn: "Bee Queen",
    season: "any", location: "草原蜂巢（需要敲击巨型蜂巢召唤）",
    health: 22500, damage: 60,
    attackPattern: ["近战攻击(60伤害)", "召唤蜜蜂(4-5只)", "尖啸（蜜蜂强化，持续10秒）", "逃跑阶段（快速移动并持续召唤蜜蜂）"],
    drops: [
      { itemName: "蜂蜜", quantity: "6-7个", dropRate: "always" },
      { itemName: "蜂王浆", quantity: "6-7个", dropRate: "always" },
      { itemName: "蜂刺", quantity: "1根", dropRate: "always" },
      { itemName: "蜂后冠", quantity: "1个", dropRate: "always" },
      { itemName: "蜂后雕塑蓝图", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "用锤子敲击草原上的巨型蜂巢（需要先清理周围的蜂巢）。建议在中后期装备齐全时挑战。",
    kitingPattern: "蜂后本体走位简单（打2-4走1），难点在于蜜蜂群的处理", minPlayersRecommended: 2,
    imagePath: "/images/bosses/bee-queen.png",
    description: "蜂后是强大的中期Boss，难度主要在于蜂群处理。蜂王浆是制作糖豆（最强回血食物之一）的核心材料，蜂后冠可以将理智转化为精神力量。",
    strategy: "1. 温蒂是最佳选择：阿比盖尔的AOE伤害清理蜂群极快\n2. 建造兔人房/猪人房在蜂后附近，帮手会清理部分蜂群\n3. 使用排箫或催眠吹箭控制蜂群\n4. 薇诺娜的投石机可以在蜂后召唤蜜蜂时自动清理\n5. 蜂后逃跑时不要追，等她回到中心\n6. 糖豆（3蜂王浆+1浆果）是持续回血120的最强食物之一",
  },
  {
    id: "eye-of-terror",
    name: "恐怖之眼", nameEn: "Eye of Terror",
    season: "any", location: "任意位置（使用恐怖之眼道具召唤）",
    health: 5000, damage: 75,
    attackPattern: ["冲锋撞击(伤害+击退)", "激光束(直线AOE)", "召唤小眼怪"],
    drops: [
      { itemName: "恐怖之眼", quantity: "1个", dropRate: "always" },
      { itemName: "恶魔肉", quantity: "2-4块", dropRate: "always" },
      { itemName: "独眼面具蓝图", quantity: "1个", dropRate: "always" },
      { itemName: "独眼炮塔蓝图", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "在陨石坑中取出恐怖之眼道具（需在陨石中找到），晚上激活召唤。如果不在天黑前击败，它会逃跑。",
    kitingPattern: "冲锋有明显轨迹——侧向闪避后反击。激光束前有蓄力动作。", minPlayersRecommended: 1,
    imagePath: "/images/bosses/eye-of-terror.png",
    description: "恐怖之眼是Terraria联动Boss——需要在夜晚召唤并在天亮前击败。击败后获得独眼面具（60%减伤+理智光环）和独眼炮塔（自动防御建筑）蓝图。两种道具都非常实用。",
    strategy: "1. 必须在傍晚召唤——确保有足够的时间在天亮前击败\n2. 独眼面具+猪皮头盔=超强防御组合\n3. 独眼炮塔是自动防御建筑——不需要电力\n4. 激光束前有明显的蓄力——注意闪避\n5. 如果天亮前没打死，它会飞走——需要重新召唤",
  },
  {
    id: "twins-of-terror",
    name: "双子恐惧", nameEn: "Twins of Terror",
    season: "any", location: "任意位置（使用两颗恐怖之眼召唤）",
    health: 10000, damage: 100,
    healthNote: "（两只各5000）",
    attackPattern: ["冲锋撞击", "激光束", "双人协同攻击", "火焰吐息（第二只）"],
    drops: [
      { itemName: "恐惧之眼", quantity: "2个", dropRate: "always" },
      { itemName: "独眼面具升级材料", quantity: "多种", dropRate: "always" },
    ],
    spawnConditions: "同时使用两颗恐怖之眼在夜晚召唤。同时面对两只眼睛，难度翻倍。",
    kitingPattern: "优先击杀一只，减少双目标压力。注意避开交叉的激光束。", minPlayersRecommended: 2,
    imagePath: "/images/bosses/twins-of-terror.png",
    description: "双子恐惧是恐怖之眼的进阶版本——同时面对两只。击败后可获得强化版独眼面具（70%减伤）和强化炮塔。双倍挑战，双倍奖励。",
    strategy: "1. 集中火力优先击杀一只\n2. 注意两只的激光束会交叉形成死角\n3. 冰杖冻住一只减轻压力\n4. 推荐2-3人团队\n5. 强化独眼面具是全游戏最好的头盔之一",
  },
  {
    id: "celestial-champion",
    name: "天体冠军", nameEn: "Celestial Champion",
    season: "any", location: "月岛（完成天体祭坛的拼装后召唤）",
    health: 22500, damage: 150,
    healthNote: "（分三阶段，每阶段7500）",
    attackPattern: ["第一阶段：远程激光+召唤月亮生物", "第二阶段：近战AOE+范围陷阱", "第三阶段：分身攻击+全场AOE+月光炮"],
    drops: [
      { itemName: "启迪王冠碎片", quantity: "3个", dropRate: "always" },
      { itemName: "纯粹辉煌", quantity: "6-10个", dropRate: "always" },
      { itemName: "月亮石", quantity: "10-15个", dropRate: "always" },
      { itemName: "天体宝箱（内含稀有物品）", quantity: "1个", dropRate: "always" },
    ],
    spawnConditions: "在月岛完成三个天体祭坛的拼装（需要在世界各地收集天体碎片），然后在天体裂缝处召唤。",
    kitingPattern: "三阶段机制各不相同——第一阶段远程输出，第二阶段贴身走位，第三阶段全场躲避", minPlayersRecommended: 3,
    imagePath: "/images/bosses/celestial-champion.png",
    description: "天体冠军是游戏最终Boss之一——分为三个阶段，每个阶段拥有全新的攻击模式。击败后可获得启迪王冠碎片（合成启迪王冠——最强大的头部装备），以及纯粹辉煌（制作终极月亮装备的核心材料）。",
    strategy: "1. 三个阶段需要不同的应对策略——准备全面\n2. 第一阶段：注意躲避激光（有明显弹道）\n3. 第二阶段：贴身走位输出（打2走1）\n4. 第三阶段：全屏AOE时躲到场地边缘\n5. 启迪王冠是全游戏最强头部装备——+400理智+发光+启迪光环\n6. 强烈推荐3-4人团队——这是最难的Boss之一",
  },
  {
    id: "shadow-pieces",
    name: "暗影三兄弟", nameEn: "Shadow Pieces",
    season: "any", location: "任意位置（使用暗影棋子+大理石雕塑召唤）",
    health: 12000, damage: 75,
    healthNote: "（战车8000+主教4000+骑士4000）",
    attackPattern: ["暗影战车(主教)：远程暗影弹幕", "暗影主教(骑士)：近战冲撞", "暗影骑士(战车)：AOE扫击", "三者配合极其致命"],
    drops: [
      { itemName: "暗影心脏", quantity: "1个", dropRate: "always" },
      { itemName: "暗影燃料", quantity: "6-10个", dropRate: "always" },
      { itemName: "暗影棋子（可重复挑战）", quantity: "各1个", dropRate: "always" },
    ],
    spawnConditions: "在大理石雕塑群上摆放正确的暗影棋子（在满月/新月时雕塑会变化），然后敲击触发。",
    kitingPattern: "优先击杀暗影主教（远程弹幕最烦），最后杀暗影战车。逐个击破。", minPlayersRecommended: 2,
    imagePath: "/images/bosses/shadow-pieces.png",
    description: "暗影三兄弟是获取暗影心脏的唯一途径——暗影心脏是召唤远古编织者（Ancient Fuelweaver）的必要道具。三个Boss各有不同能力且会互相配合，是经典的多目标Boss战。",
    strategy: "1. 击杀顺序：暗影主教→暗影骑士→暗影战车\n2. 暗影主教的远程弹幕伤害高——优先解决\n3. 冰杖冻住一个后逐个击破\n4. 击杀后获得暗影心脏——这是挑战远古编织者的门票\n5. 三兄弟的配合是最大威胁——用冰杖/睡眠控制来分割战场",
  },
];
