import { Character } from "@/types";

export const characters: Character[] = [
  // ==================== 初始免费角色 ====================
  {
    id: "wilson",
    name: "威尔逊", nameEn: "Wilson",
    tagline: "绅士科学家",
    difficulty: "beginner", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "长出胡须", description: "随时间生长胡须，可剃须获得胡须，胡须提供保暖效果", icon: "beard" },
      { name: "炼金知识", description: "可以制作各种科学物品，是基础的科技角色", icon: "science" },
      { name: "炼金转换（技能树）", description: "可将材料在矿石/宝石/树枝之间互相转换", icon: "transmute" },
    ],
    quirks: ["无特殊限制"],
    bestFor: ["新手入门", "均衡发展", "冬季生存", "资源转换"],
    imagePath: "/images/characters/wilson.png",
    description: "威尔逊是饥荒的基础角色，拥有均衡的三围属性。他最大的特色是技能树中的炼金转换能力——可以将树枝变成矿石，矿石变成宝石，实现资源的灵活调配。胡须在冬季可以提供保暖。",
    tips: ["冬季前不要剃须，胡须提供保暖很关键", "夏季可以剃须来降温", "胡须可以用来制作肉像（复活道具）", "技能树点满后可以做终极炼金：树枝变铥矿", "适合学习游戏基础机制"],
  },
  {
    id: "willow",
    name: "薇洛", nameEn: "Willow",
    tagline: "纵火者",
    difficulty: "beginner", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 120 },
    damageModifier: 1.0,
    perks: [
      { name: "打火机", description: "初始携带耐久无限的打火机，可照明和点燃物品", icon: "lighter" },
      { name: "火焰免疫", description: "对火焰伤害免疫，站在火旁回复理智", icon: "fire" },
      { name: "伯尼", description: "理智低时，手中的伯尼熊会变大并吸引怪物仇恨+造成AOE火焰伤害", icon: "bernie" },
      { name: "火焰法术（技能树）", description: "可以施放火球和火焰光环，造成范围伤害", icon: "spell" },
    ],
    quirks: ["理智较低（120）", "理智低时会自动点燃脚下物品（可技能树控制）", "火焰伤害加成"],
    bestFor: ["洞穴探索", "冬季生存", "战斗支援", "范围清怪"],
    imagePath: "/images/characters/willow.png",
    description: "薇洛是火焰专家，对火焰伤害免疫。她的打火机是无限耐久的便携光源。伯尼熊在理智低时会自动保护她并造成AOE火焰伤害。技能树解锁后可主动施放火球和火焰光环，是极强的AOE角色。",
    tips: ["打火机是非常实用的无限光源", "理智低时不要慌，伯尼会保护你", "注意不要在家附近低理智状态，会引发火灾", "伯尼可以升级为暗影/月亮伯尼，战斗力极强", "技能树的火焰光环清理蜘蛛/蜜蜂群极快"],
  },
  {
    id: "wendy",
    name: "温蒂", nameEn: "Wendy",
    tagline: "迷途者",
    difficulty: "beginner", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 0.75,
    perks: [
      { name: "阿比盖尔", description: "初始携带阿比盖尔之花，可召唤双胞胎姐姐的灵魂协助战斗", icon: "abigail" },
      { name: "群体伤害", description: "阿比盖尔的攻击是AOE伤害，适合清理大量小型怪物", icon: "aoe" },
      { name: "阿比盖尔强化（技能树）", description: "阿比盖尔可升级获得暗影/月亮形态，解锁新攻击方式", icon: "upgrade" },
    ],
    quirks: ["自身伤害只有正常的75%", "黑暗理智损失减少25%", "与阿比盖尔一起战斗时获得额外伤害加成"],
    bestFor: ["清蜘蛛", "刷肉", "新手过渡", "蜂后杀手", "青蛙雨"],
    imagePath: "/images/characters/wendy.png",
    description: "温蒂自身攻击力较弱（75%），但可以召唤姐姐阿比盖尔。阿比盖尔白天伤害15，黄昏25，夜晚40，且攻击为AOE。技能树中阿比盖尔可获得暗影或月亮形态，解锁冲刺攻击和范围爆炸。温蒂是清蜘蛛、蜜蜂等小型怪物的最佳选择。",
    tips: ["阿比盖尔夜晚伤害最高，尽量晚上打怪", "阿比盖尔之花可以制作成阿比盖尔之花灵药来强化", "温蒂黑暗理智损失少，可以少带光源物品", "技能树点出阿比盖尔自愈后，她的续航极强", "暗影形态阿比盖尔打Boss单体伤害更高"],
  },
  {
    id: "wigfrid",
    name: "薇格弗德", nameEn: "Wigfrid",
    tagline: "表演艺术家",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 200, hunger: 120, sanity: 120 },
    damageModifier: 1.25,
    perks: [
      { name: "战斗回血", description: "每次攻击敌人回复少量生命值和理智值", icon: "lifesteal" },
      { name: "专属装备", description: "可以制作战斗长矛和战斗头盔，比普通装备更好", icon: "gear" },
      { name: "伤害加成", description: "天生25%伤害加成，吃肉类食物效果更好", icon: "damage" },
      { name: "战斗之歌（技能树）", description: "可吟唱战斗之歌，为团队提供多种增益效果", icon: "song" },
    ],
    quirks: ["只能吃肉食", "饥饿值较低（120）"],
    bestFor: ["Boss战斗", "团队输出", "坦克", "团队辅助"],
    imagePath: "/images/characters/wigfrid.png",
    description: "薇格弗德是战斗专家，拥有25%伤害加成和攻击回血回理智能力。只能吃肉食，但肉类对她效果更好。技能树解锁战斗之歌系统——可吟唱回血歌、武器耐久歌、火焰抗性歌等多种团队增益，是最强的团队辅助之一。",
    tips: ["找猪人村或蜘蛛巢保证肉类供应", "战斗长矛+战斗头盔是前期最佳装备", "攻击回血机制让她的续航能力极强", "战斗之歌在团队Boss战中至关重要", "可以制作多种不同的战斗之歌卷轴"],
  },
  {
    id: "wolfgang",
    name: "沃尔夫冈", nameEn: "Wolfgang",
    tagline: "大力士",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 200, hunger: 300, sanity: 200 },
    damageModifier: 2.0,
    perks: [
      { name: "力量形态", description: "饱食度高时体型变大，伤害最高2倍，速度加快", icon: "mighty" },
      { name: "重击（技能树）", description: "可以投掷哑铃造成范围伤害，解锁新的战斗技能", icon: "throw" },
      { name: "工作效率", description: "力量形态下采矿、伐木效率大幅提升", icon: "work" },
    ],
    quirks: ["饥饿消耗快1.5倍", "饱食度低时伤害降至0.5倍", "害怕黑暗（理智损失快1.1倍）"],
    bestFor: ["Boss速杀", "单人输出", "伐木采矿"],
    imagePath: "/images/characters/wolfgang.png",
    description: "沃尔夫冈是游戏中伤害最高的角色，满饱食时可达到2倍伤害。饥饿消耗快，需要大量食物维持。技能树解锁后可以投掷哑铃进行远程AOE攻击，满饱食时工作效率极高——伐木采矿速度翻倍。",
    tips: ["保持饱食度在250以上维持满buff", "搭配Warly的辣味料理可以打出爆炸输出", "平常做杂活可以维持较低饱食度", "需要大量食物供应，建议建立稳定的食物生产线", "技能树中的重击技能可以远程拉扯Boss"],
  },
  {
    id: "wx78",
    name: "WX-78", nameEn: "WX-78",
    tagline: "机器人",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 150 },
    damageModifier: 1.0,
    perks: [
      { name: "齿轮升级", description: "吃齿轮可以永久提升属性（最高400血/200饥饿/300理智）", icon: "gear" },
      { name: "电路系统（技能树）", description: "可用生物数据制作电路模块，安装到身体获得各种加成", icon: "circuit" },
      { name: "电荷免疫", description: "被雷击后进入过载状态，移速加快且发光，损失理智", icon: "lightning" },
      { name: "不怕腐烂", description: "吃变质食物/冰块不受惩罚", icon: "rot" },
    ],
    quirks: ["雨水会造成伤害（非防水机器人）", "初始属性较低需要升级"],
    bestFor: ["世界探索", "长期存档", "多功能配置"],
    imagePath: "/images/characters/wx78.png",
    description: "WX-78是成长型角色，初始属性较低但可通过齿轮升级。技能树解锁电路系统——可安装多达6个电路模块，包括加速模块、夜视模块、保温/隔热模块、音乐盒（回理智）等，实现高度自定义的功能配置。",
    tips: ["尽早下洞穴杀发条生物收集齿轮", "眼球伞是必备装备，防止雨水伤害", "过载状态是免费的移动光源和加速", "技能树的夜视模块可以永久夜视，洞穴探索神器", "电路模块可以随时更换来适应不同场景"],
  },
  {
    id: "wickerbottom",
    name: "薇克巴顿", nameEn: "Wickerbottom",
    tagline: "图书管理员",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 250 },
    damageModifier: 1.0,
    perks: [
      { name: "科学达人", description: "无需科学机器即可制作一级物品，自带一本科技", icon: "science" },
      { name: "魔法书", description: "可制作多种魔法书：应用园艺（催生植物）、万物之始（召唤触手）等", icon: "book" },
      { name: "不眠不休", description: "不能通过睡觉恢复理智，但可以用书回理智", icon: "insomnia" },
    ],
    quirks: ["不能睡觉（帐篷等无效）", "吃变质食物惩罚加倍"],
    bestFor: ["资源生产", "触手农场", "团队辅助", "高级玩家"],
    imagePath: "/images/characters/wickerbottom.png",
    description: "薇克巴顿是书本魔法师，可以制作各种功能强大的魔法书。应用园艺可以瞬间催熟一片农作物；万物之始可以召唤触手群；永恒之光提供全屏照明。不能睡觉但可以靠《克服蛛形恐惧症》回理智。",
    tips: ["应用园艺+鸟笼是最强的食物生产系统", "触手书可以建造触手农场自动刷肉", "永恒之光书在Boss战提供稳定照明", "不适合新手——需要大量芦苇和羽毛来制作书籍", "搭配WX-78的过载，触手农场效率翻倍"],
  },
  {
    id: "wes",
    name: "韦斯", nameEn: "Wes",
    tagline: "哑巴（默剧演员）",
    difficulty: "challenge", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 113, hunger: 113, sanity: 150 },
    damageModifier: 0.75,
    perks: [
      { name: "气球", description: "可以消耗5点理智吹气球（最多100个），气球可吸引怪物仇恨或装饰", icon: "balloon" },
      { name: "隐形自行车", description: "可以吹出气球自行车，短暂的加速移动效果", icon: "speed" },
    ],
    quirks: ["三围最低（113/113/150）", "伤害只有正常人75%", "饥饿消耗快1.25倍", "不会说话（无语音提示）", "高温/低温时额外损失更多生命"],
    bestFor: ["挑战自我", "团队吉祥物", "硬核模式"],
    imagePath: "/images/characters/wes.png",
    description: "韦斯是饥荒的自虐角色——三围最低、伤害最弱、饥饿更快，几乎没有任何正面能力。他的存在就是为了增加游戏难度。气球是他唯一的特色：可以吹气球吸引怪物注意，或做装饰。适合追求极限挑战的玩家。",
    tips: ["不要选——除非你想挑战自我", "气球可以短暂吸引Boss仇恨", "团队中韦斯基本是拖油瓶", "隐形自行车是唯一的保命技能", "适合在服务器中当吉祥物"],
  },
  {
    id: "maxwell",
    name: "麦斯威尔", nameEn: "Maxwell",
    tagline: "暗影之王",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 75, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "暗影分身", description: "可召唤暗影分身：暗影工人（采集/挖掘/伐木）和暗影战士（战斗）", icon: "shadow" },
      { name: "暗影装备", description: "可以制作暗影剑和暗影甲（比普通版更强）", icon: "gear" },
      { name: "理智回复", description: "天生每分钟回复+6.67理智（非常高）", icon: "sanity" },
    ],
    quirks: ["血量只有75（极低！）", "暗影分身持续消耗理智和噩梦燃料"],
    bestFor: ["资源采集", "快速建家", "高端玩家"],
    imagePath: "/images/characters/maxwell.png",
    description: "麦斯威尔是暗影魔法大师——血量只有75，但可以召唤多达多个暗影分身同时工作。暗影工人可以伐木、采矿、挖掘（比人手还快），暗影战士可以自动战斗。天生高理智回复，搭配暗影装备使用更强。是资源采集第一人。",
    tips: ["暗影工人同时伐木/采矿效率远超人工", "血量极低，打Boss必须穿顶级护甲", "暗影分身消耗噩梦燃料，需要定期补充", "搭配蜂后冠可以更有效管理理智", "暗影牢笼可以困住Boss数秒——极强的控制技能"],
  },
  {
    id: "woodie",
    name: "伍迪", nameEn: "Woodie",
    tagline: "伐木工",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "露西斧", description: "初始携带会说话的斧头——露西，砍树速度极快，露西会提醒你各种事情", icon: "axe" },
      { name: "变身（技能树）", description: "吃变身符可变成海狸（高速砍树）、驼鹿（战斗）、或大鹅（探图/水上行走）", icon: "transform" },
      { name: "树木之力", description: "变身状态下拥有独立血量和特殊能力", icon: "tree" },
    ],
    quirks: ["满月会强制变身", "变身符需要消耗木头制作"],
    bestFor: ["伐木", "探图", "Boss战（驼鹿形态）"],
    imagePath: "/images/characters/woodie.png",
    description: "伍迪是变形大师。露西斧砍树速度是普通斧头的两倍以上，且露西会说话（提供语音提示）。吃变身符后可变成三种形态：海狸——砍树挖矿掘地无所不能；驼鹿——高血量高伤害，可冲锋撞击；大鹅——跑速极快，可水上行走。",
    tips: ["海狸形态砍树极快，配合应用园艺种树效率逆天", "驼鹿形态冲锋可以打断Boss技能", "大鹅可以在海上奔跑——探图神器", "满月记得做好准备，会被强制变身", "变身期间本体不会饥饿，可以利用这一点节食"],
  },
  {
    id: "webber",
    name: "韦伯", nameEn: "Webber",
    tagline: "蜘蛛男孩",
    difficulty: "beginner", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 175, hunger: 175, sanity: 100 },
    damageModifier: 1.0,
    perks: [
      { name: "蜘蛛之友", description: "蜘蛛不会攻击韦伯，可以收买蜘蛛为随从", icon: "spider" },
      { name: "蜘蛛巢", description: "可以制作蜘蛛巢，在任何地方建造蜘蛛农场", icon: "nest" },
      { name: "吃怪物肉", description: "可以安全吃怪物肉（无惩罚）", icon: "monster" },
      { name: "蜘蛛丝胡须", description: "剃胡须获得蜘蛛丝", icon: "silk" },
    ],
    quirks: ["猪人、兔人、猫猫等被动生物会主动攻击韦伯", "理智较低（100）"],
    bestFor: ["蜘蛛农场", "刷肉", "刷腺体", "Boss战（蜘蛛大军）"],
    imagePath: "/images/characters/webber.png",
    description: "韦伯是蜘蛛的朋友——蜘蛛不攻击他，可以收买蜘蛛为随从并带领蜘蛛大军作战。可以制作蜘蛛巢在任何地方进行蜘蛛农场。能吃怪物肉无惩罚，怪物肉是他最好的食物。猪人、兔人等会主动攻击韦伯，需要避开。",
    tips: ["收买大量蜘蛛→带去清Boss（蜘蛛海战术）", "蜘蛛巢+猪人房不要建在一起", "怪物肉当主食——可以不建农场纯吃怪物肉", "蜘蛛腺体无限供应——回血药随便吃", "可以制作蜘蛛帽伪装成蜘蛛（其他角色也能用）"],
  },
  {
    id: "winona",
    name: "薇诺娜", nameEn: "Winona",
    tagline: "工程师",
    difficulty: "intermediate", isDlc: false, unlockMethod: "初始可用",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "投石机（技能树）", description: "可以建造投石机自动攻击敌人，需要电力/发电机供能", icon: "catapult" },
      { name: "快速建造", description: "在黑暗/雨天中也能正常建造", icon: "build" },
      { name: "发电机", description: "可制作发电机为投石机供电，也可充电给队友的电子设备", icon: "generator" },
    ],
    quirks: ["第一次被攻击会触发短暂无敌", "建造速度比其他人快"],
    bestFor: ["Boss自动化", "基地防御", "团队后勤"],
    imagePath: "/images/characters/winona.png",
    description: "薇诺娜是工程师，核心能力是建造投石机——自动瞄准攻击范围内的任何敌人。需要发电机或电力网络供能。多台投石机可以组成自动防御阵地，Boss战中提供恐怖的自动输出。技能树可解锁更多投石机升级和电力网络。",
    tips: ["投石机+石墙=自动化Boss农场", "多台投石机阵地的输出堪比3个人的DPS", "发电机可以给WX-78充电触发过载", "技能树中的投石机升级（冰冻/火焰弹）极强", "黑暗/雨中建造的能力在洞穴和春天很好用"],
  },
  // ==================== DLC/编织角色 ====================
  {
    id: "wormwood",
    name: "沃姆伍德", nameEn: "Wormwood",
    tagline: "植物人",
    difficulty: "intermediate", isDlc: true, unlockMethod: "编织/购买（需要2700线轴）",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "光合作用", description: "白天自动回血（阳光），可以种地不消耗种子", icon: "sun" },
      { name: "植物制作（技能树）", description: "可以制作活木、荆棘陷阱、孢子炸弹等各种植物道具", icon: "craft" },
      { name: "开花状态", description: "进入开花状态后移速加快，自动回复周围植物的生长", icon: "bloom" },
    ],
    quirks: ["不能通过食物回血（但可以通过肥料/堆肥回血）", "食物可以补充饱食度但不能补血", "会被蜜蜂/蝴蝶等生物喜欢跟着他走"],
    bestFor: ["种地", "团队后勤", "植物道具制作", "活木供应"],
    imagePath: "/images/characters/wormwood.png",
    description: "沃姆伍德是植物人——不能用食物回血，但可以通过肥料、堆肥、蜂蜜膏药、蜘蛛腺体等方式回血。可以种地不消耗种子（徒手播种），开花状态加速周围植物生长。技能树解锁后的荆棘陷阱和孢子炸弹是强力的范围攻击手段。",
    tips: ["堆肥是最经济的回血方式——腐烂食物即可制作", "开花状态下种地效率最高", "徒手播种不需要种子——可以快速扩大农场", "活木是稀缺资源，沃姆伍德可以无限制作", "搭配Wickerbottom的应用园艺可以实现超大规模种植"],
  },
  {
    id: "wortox",
    name: "沃托克斯", nameEn: "Wortox",
    tagline: "小恶魔",
    difficulty: "intermediate", isDlc: true, unlockMethod: "编织/购买（需要2700线轴）",
    stats: { health: 200, hunger: 175, sanity: 150 },
    damageModifier: 1.0,
    perks: [
      { name: "灵魂跳跃", description: "消耗灵魂进行短距离瞬间移动（可穿越地形/水面）", icon: "teleport" },
      { name: "灵魂收集", description: "击杀生物掉落灵魂（最多20个），灵魂可用于回血、跳跃或释放", icon: "soul" },
      { name: "灵魂治疗", description: "释放灵魂可以群体回血（AOE治疗）", icon: "heal" },
    ],
    quirks: ["食物效果减半（包括正面和负面效果）", "可以吃灵魂来维持饥饿", "猪人/兔人会主动攻击"],
    bestFor: ["探图", "团队治疗", "跑图速通"],
    imagePath: "/images/characters/wortox.png",
    description: "沃托克斯是灵魂恶魔——击杀任何生物都会掉落灵魂。灵魂可以用于瞬间移动（短距离闪现，可穿墙穿水）、自我回血（每个+20血）、或释放AOE治疗（群体回血）。食物效果只有正常的一半，但灵魂可以补充一切。",
    tips: ["灵魂跳跃是游戏中最强的位移技能", "AOE治疗在团队Boss战中极其重要", "杀蝴蝶/蜜蜂等小生物是最快的灵魂获取方式", "灵魂最多存20个——满了就释放治疗", "可以穿越水面上岛——不造船探图"],
  },
  {
    id: "wurt",
    name: "沃特", nameEn: "Wurt",
    tagline: "鱼人女孩",
    difficulty: "advanced", isDlc: true, unlockMethod: "编织/购买（需要2700线轴）",
    stats: { health: 150, hunger: 200, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "鱼人王国（技能树）", description: "可以建造鱼人房、任命鱼人王，建立自己的鱼人军队", icon: "merm" },
      { name: "鱼人随从", description: "喂食鱼人可使其成为随从（比猪人更强壮）", icon: "follower" },
      { name: "水生优势", description: "在水中移速不减，可以携带鱼人游泳", icon: "water" },
    ],
    quirks: ["只能吃素食", "不能和猪人交易"],
    bestFor: ["鱼人大军", "Boss速杀", "建家扩展"],
    imagePath: "/images/characters/wurt.png",
    description: "沃特是鱼人公主——可以建造鱼人房并招募鱼人随从。经过技能树强化后的鱼人王可以提供恐怖的范围增益，鱼人大军是游戏中最强的随从军队。只能吃素食，但素食种类丰富。水中移速不减是她独特的优势。",
    tips: ["鱼人王是游戏中最强的随从buff来源", "20+鱼人大军可以碾压几乎所有Boss", "素食中饺子（+蘑菇+蛋+肉）不能吃——但可用纯素食配方", "鱼人可以在水中跟随——海洋Boss战的王者", "技能树的鱼人王升级效果可以叠加——后期极强"],
  },
  {
    id: "walter",
    name: "沃尔特", nameEn: "Walter",
    tagline: "童子军",
    difficulty: "intermediate", isDlc: true, unlockMethod: "编织/购买（需要2700线轴）",
    stats: { health: 130, hunger: 110, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "沃比", description: "初始携带宠物狗沃比，可骑行（加速移动），沃比可以变大变小", icon: "woby" },
      { name: "弹弓（技能树）", description: "可以使用弹弓配合多种弹药进行远程攻击", icon: "slingshot" },
      { name: "野外故事", description: "在营火旁可以讲野外故事，为团队回复理智", icon: "story" },
    ],
    quirks: ["被击中会额外损失理智", "血量较低（130）", "有过敏反应（被蜜蜂攻击受伤更多）"],
    bestFor: ["远程战斗", "探图", "团队理智回复"],
    imagePath: "/images/characters/walter.png",
    description: "沃尔特是童子军——拥有弹弓可以进行安全的远程攻击（不吸引仇恨！），多种弹药（石子、黄金弹、冰弹、粪弹、减速弹等）提供不同效果。骑乘沃比快速探图。在营火旁讲故事为团队回复理智。技能树大幅强化弹弓和沃比。",
    tips: ["弹弓远程攻击不会拉Boss仇恨——最安全的输出方式", "多种弹药应对不同场景：冰弹控制、黄金弹输出", "沃比可以携带额外背包空间（变大后）", "讲故事是团队回复理智的免费方式", "被蜜蜂克——避开蜂后和杀人蜂"],
  },
  {
    id: "wanda",
    name: "旺达", nameEn: "Wanda",
    tagline: "时间旅行者",
    difficulty: "advanced", isDlc: true, unlockMethod: "编织/购买（需要2700线轴）",
    stats: { health: 150, hunger: 150, sanity: 200 },
    damageModifier: 1.0,
    perks: [
      { name: "时间魔法", description: "没有常规血量——使用年龄系统，越老伤害越高但越脆", icon: "time" },
      { name: "回溯表", description: "可制作多种表：回溯表（回退自身位置和时间）、裂缝表（传送）、警报表（陷阱）等", icon: "watch" },
      { name: "暗影表", description: "暗影表是游戏中最强的武器之一——越老伤害越高", icon: "weapon" },
    ],
    quirks: ["年龄代替血量（青年→中年→老年→死亡）", "越老攻击力越高（最高+250%）", "越老越脆弱（生命消耗加快）"],
    bestFor: ["Boss速杀", "高端玩家", "位置回溯", "传送"],
    imagePath: "/images/characters/wanda.png",
    description: "旺达是最独特的角色——没有传统的血量系统，用年龄代替。越老攻击力越高（暗影表在老年状态可以打出250+伤害！），但消耗也越快。回溯表可以回到数秒前的位置和年龄（绝地逃生），裂缝表可以远距离传送。操作天花板极高。",
    tips: ["老年状态+暗影表的伤害是全游戏天花板", "回溯表是被打后立刻回退的保命神技", "裂缝表可以在地图上任意两点之间传送", "需要经常用不老表来维持在最佳年龄区间", "难度极高——不适合新手，但高手的输出之王"],
  },
];
