import { CrockPotRecipe } from "@/types";

export const recipes: CrockPotRecipe[] = [
  // ==================== HIGH PRIORITY RECIPES (回血向) ====================
  {
    id: "butter_muffin",
    name: "奶油松饼", nameEn: "Butter Muffin",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 1, weight: 1,
    requirements: {},
    minMeat: 0, maxMeat: 0,
    requiresTags: ["dairy"], forbidsTags: ["meat"],
    notes: "需要蝴蝶翅膀+蔬菜（不是水果），不能有肉",
    imagePath: "/images/foods/butter_muffin.png",
  },
  {
    id: "dragonpie",
    name: "火龙果派", nameEn: "Dragonpie",
    category: "health", stats: { health: 40, hunger: 75, sanity: 5 },
    cookTime: 40, priority: 1, weight: 1,
    requirements: {},
    requiresSpecific: ["dragon_fruit"],
    forbidsTags: ["meat"],
    notes: "需要至少1个火龙果，不能有肉。1火龙果+3树枝即可。",
    imagePath: "/images/foods/dragonpie.png",
  },
  {
    id: "honey_ham",
    name: "蜜汁火腿", nameEn: "Honey Ham",
    category: "health", stats: { health: 30, hunger: 75, sanity: 5 },
    cookTime: 40, priority: 2, weight: 1,
    requirements: { minTags: { meat: 2.0 } },
    requiresTags: ["sweetener"],
    notes: "需要蜂蜜+2个以上的肉值。大肉(1.0)+小肉(0.5)+蜂蜜+浆果即可。",
    imagePath: "/images/foods/honey_ham.png",
  },
  {
    id: "bacon_eggs",
    name: "培根炒蛋", nameEn: "Bacon and Eggs",
    category: "health", stats: { health: 20, hunger: 75, sanity: 5 },
    cookTime: 40, priority: 10, weight: 1,
    requirements: { minTags: { meat: 1.5, egg: 2.0 } },
    minMeat: 1.5,
    notes: "需要1.5以上肉值+2.0以上蛋值。2个鸡蛋+1怪物肉+1小肉即可。",
    imagePath: "/images/foods/bacon_eggs.png",
  },
  {
    id: "pierogi",
    name: "波兰饺子", nameEn: "Pierogi",
    category: "health", stats: { health: 40, hunger: 37.5, sanity: 5 },
    cookTime: 20, priority: 5, weight: 1,
    requirements: { minTags: { egg: 1.0, vegetable: 0.5 } },
    minMeat: 0.5,
    notes: "需要1蛋+1蔬菜+0.5以上肉值。1蛋+1蘑菇+1怪物肉+1浆果即可。回血神器。",
    imagePath: "/images/foods/pierogi.png",
  },
  {
    id: "fishsticks",
    name: "鱼排", nameEn: "Fishsticks",
    category: "health", stats: { health: 40, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 10, weight: 1,
    requirements: { minTags: { fish: 0.5 } },
    minMeat: 0, maxMeat: 0,
    requiresTags: ["fish"], forbidsTags: ["meat"],
    notes: "需要鱼+树枝（至少1个树枝），不能有其他肉。1鱼+1树枝+2浆果即可。",
    imagePath: "/images/foods/fishsticks.png",
  },
  {
    id: "trail_mix",
    name: "干果拼盘", nameEn: "Trail Mix",
    category: "health", stats: { health: 30, hunger: 12.5, sanity: 5 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: {},
    requiresSpecific: ["birchnut"],
    requiresTags: ["fruit"],
    forbidsTags: ["meat", "inedible", "egg", "vegetable"],
    notes: "需要1个白桦坚果+1个浆果（其他必须也是水果或树枝）。1坚果+1浆果+2树枝。",
    imagePath: "/images/foods/trail_mix.png",
  },
  {
    id: "surf_n_turf",
    name: "海陆大餐", nameEn: "Surf 'n' Turf",
    category: "health", stats: { health: 60, hunger: 37.5, sanity: 33 },
    cookTime: 10, priority: 30, weight: 1,
    requirements: { minTags: { meat: 2.5, fish: 1.5 } },
    minMeat: 2.5,
    notes: "需要2.5以上肉值+1.5以上鱼值。1大肉+1怪物肉+2鱼=回血60！最强回血食谱。",
    imagePath: "/images/foods/surf_n_turf.png",
  },
  {
    id: "flower_salad",
    name: "花式沙拉", nameEn: "Flower Salad",
    category: "health", stats: { health: 40, hunger: 12.5, sanity: 5 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: {},
    requiresSpecific: ["cactus_flesh"],
    forbidsTags: ["meat"],
    notes: "需要仙人掌肉+蔬菜。1仙人掌肉+3浆果即可。回血不错。",
    imagePath: "/images/foods/flower_salad.png",
  },
  {
    id: "beefy_greens",
    name: "牛肉绿叶", nameEn: "Beefy Greens",
    category: "health", stats: { health: 40, hunger: 75, sanity: 5 },
    cookTime: 40, priority: 25, weight: 1,
    requirements: { minTags: { vegetable: 3.0 } },
    requiresSpecific: ["leafy_meat"],
    forbidsTags: ["meat"],
    notes: "需要叶肉+3蔬菜。1叶肉+3萝卜即可。叶肉不算肉标签！",
    imagePath: "/images/foods/beefy_greens.png",
  },
  {
    id: "jellybeans",
    name: "糖豆", nameEn: "Jellybeans",
    category: "utility", stats: { health: 122, hunger: 0, sanity: 5 },
    cookTime: 50, priority: 12, weight: 1,
    requirements: {},
    requiresSpecific: ["royal_jelly"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要蜂王浆。3蜂王浆+1浆果。持续回血122点（2分钟），最强回血食物！",
    imagePath: "/images/foods/jellybeans.png",
  },
  // ==================== HUNGER RECIPES (饱食向) ====================
  {
    id: "meaty_stew",
    name: "大肉汤", nameEn: "Meaty Stew",
    category: "hunger", stats: { health: 12, hunger: 150, sanity: 5 },
    cookTime: 15, priority: 0, weight: 1,
    requirements: { minTags: { meat: 3.0 } },
    minMeat: 3.0, maxMeat: 10,
    notes: "需要3.0以上的肉值。3个大肉+1个填充物即可。",
    imagePath: "/images/foods/meaty_stew.png",
  },
  {
    id: "meatballs",
    name: "肉丸", nameEn: "Meatballs",
    category: "hunger", stats: { health: 3, hunger: 62.5, sanity: 5 },
    cookTime: 15, priority: -1, weight: 1,
    requirements: { minTags: { meat: 0.5 } },
    minMeat: 0.5, maxMeat: 100,
    forbidsTags: ["inedible"],
    notes: "最简单的主食。1怪物肉+3浆果即可。性价比最高。",
    imagePath: "/images/foods/meatballs.png",
  },
  {
    id: "honey_nuggets",
    name: "蜂蜜肉块", nameEn: "Honey Nuggets",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 2, weight: 1,
    requirements: { minTags: { meat: 0.5 } },
    minMeat: 0.5, maxMeat: 100,
    requiresTags: ["sweetener"],
    notes: "需要肉+蜂蜜。1怪物肉+1蜂蜜+2浆果即可。",
    imagePath: "/images/foods/honey_nuggets.png",
  },
  {
    id: "turkey_dinner",
    name: "火鸡大餐", nameEn: "Turkey Dinner",
    category: "health", stats: { health: 20, hunger: 75, sanity: 5 },
    cookTime: 60, priority: 10, weight: 1,
    requirements: { minTags: { meat: 0.5 } },
    requiresSpecific: ["drumstick"],
    notes: "需要鸡腿+肉+蔬菜/水果。2鸡腿+1怪物肉+1浆果即可。",
    imagePath: "/images/foods/turkey_dinner.png",
  },
  {
    id: "spicy_chili",
    name: "辣味炖菜", nameEn: "Spicy Chili",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 0 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: { minTags: { meat: 1.5, vegetable: 1.5 } },
    minMeat: 1.5,
    notes: "需要肉+蔬菜。2大肉+2胡萝卜即可。",
    imagePath: "/images/foods/spicy_chili.png",
  },
  {
    id: "kabobs",
    name: "烤肉串", nameEn: "Kabobs",
    category: "hunger", stats: { health: 3, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 4, weight: 1,
    requirements: { minTags: { meat: 0.5 } },
    minMeat: 0.5, maxMeat: 3.0,
    requiresTags: ["inedible"],
    notes: "需要肉+树枝。1怪物肉+1树枝+2浆果即可。早期好用。",
    imagePath: "/images/foods/kabobs.png",
  },
  {
    id: "froggle_bunwich",
    name: "蛙腿三明治", nameEn: "Froggle Bunwich",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 1, weight: 1,
    requirements: {},
    requiresSpecific: ["frog_legs"],
    notes: "需要蛙腿+蔬菜。1蛙腿+1蘑菇+2浆果即可。",
    imagePath: "/images/foods/froggle_bunwich.png",
  },
  // ==================== SANITY RECIPES (理智向) ====================
  {
    id: "taffy",
    name: "太妃糖", nameEn: "Taffy",
    category: "sanity", stats: { health: -3, hunger: 25, sanity: 15 },
    cookTime: 40, priority: 10, weight: 1,
    requirements: { minTags: { sweetener: 3.0 } },
    minMeat: 0, maxMeat: 0,
    requiresTags: ["sweetener"], forbidsTags: ["meat"],
    notes: "需要3个蜂蜜。3蜂蜜+1浆果即可。回理智神器。",
    imagePath: "/images/foods/taffy.png",
  },
  {
    id: "pumpkin_cookies",
    name: "南瓜饼干", nameEn: "Pumpkin Cookies",
    category: "sanity", stats: { health: 0, hunger: 37.5, sanity: 15 },
    cookTime: 40, priority: 10, weight: 1,
    requirements: { minTags: { sweetener: 2.0 } },
    requiresSpecific: ["pumpkin"],
    forbidsTags: ["meat"],
    notes: "需要南瓜+2蜂蜜。1南瓜+2蜂蜜+1树枝即可。回理智效果好。",
    imagePath: "/images/foods/pumpkin_cookies.png",
  },
  {
    id: "ice_cream",
    name: "冰淇淋", nameEn: "Ice Cream",
    category: "sanity", stats: { health: 0, hunger: 25, sanity: 50 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: { minTags: { dairy: 1.0, sweetener: 1.0 } },
    minMeat: 0, maxMeat: 0,
    requiresTags: ["dairy", "sweetener"], forbidsTags: ["meat", "inedible", "vegetable"],
    notes: "需要乳制品+糖+冰。1黄油/电羊奶+1蜂蜜+2冰块。回50理智顶级！",
    imagePath: "/images/foods/ice_cream.png",
  },
  {
    id: "melon_sicle",
    name: "西瓜冰棒", nameEn: "Melonsicle",
    category: "sanity", stats: { health: 3, hunger: 12.5, sanity: 20 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: { minTags: { fruit: 0.5 } },
    requiresSpecific: ["watermelon"],
    requiresTags: ["filler"],
    forbidsTags: ["meat", "inedible", "vegetable"],
    notes: "需要西瓜+冰+树枝。1西瓜+1冰+2树枝即可。夏天好选择。",
    imagePath: "/images/foods/melonsicle.png",
  },
  {
    id: "banana_pop",
    name: "香蕉冰棒", nameEn: "Banana Pop",
    category: "sanity", stats: { health: 20, hunger: 12.5, sanity: 33 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fruit: 1.0 } },
    requiresSpecific: ["banana"],
    requiresTags: ["filler"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要香蕉+冰+树枝。1香蕉+1冰+2树枝。回33理智顶级！",
    imagePath: "/images/foods/banana_pop.png",
  },
  {
    id: "vegetable_stinger",
    name: "蔬菜鸡尾酒", nameEn: "Vegetable Stinger",
    category: "sanity", stats: { health: 3, hunger: 12.5, sanity: 33 },
    cookTime: 10, priority: 15, weight: 1,
    requirements: { minTags: { vegetable: 1.0 } },
    requiresSpecific: ["asparagus", "tomato"],
    requiresTags: ["filler"],
    notes: "需要芦笋/番茄+冰+蔬菜。回33理智的素食选择。",
    imagePath: "/images/foods/vegetable_stinger.png",
  },
  {
    id: "jelly_salad",
    name: "果冻沙拉", nameEn: "Jelly Salad",
    category: "sanity", stats: { health: 3, hunger: 37.5, sanity: 50 },
    cookTime: 40, priority: 50, weight: 1,
    requirements: { minTags: { sweetener: 2.0 } },
    requiresSpecific: ["leafy_meat"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要叶肉+2蜂蜜。1叶肉+2蜂蜜+1浆果。回50理智最强之一！",
    imagePath: "/images/foods/jelly_salad.png",
  },
  // ==================== STANDARD RECIPES ====================
  {
    id: "ratatouille",
    name: "蔬菜杂烩", nameEn: "Ratatouille",
    category: "health", stats: { health: 3, hunger: 25, sanity: 5 },
    cookTime: 20, priority: 0, weight: 1,
    requirements: { minTags: { vegetable: 0.5 } },
    minMeat: 0, maxMeat: 0,
    forbidsTags: ["meat", "inedible"],
    notes: "1蘑菇+3浆果即可，素食可用。",
    imagePath: "/images/foods/ratatouille.png",
  },
  {
    id: "fist_full_of_jam",
    name: "果酱", nameEn: "Fist Full of Jam",
    category: "health", stats: { health: 3, hunger: 37.5, sanity: 5 },
    cookTime: 10, priority: 0, weight: 1,
    requirements: { minTags: { fruit: 0.5 } },
    minMeat: 0, maxMeat: 0,
    forbidsTags: ["meat", "inedible", "vegetable"],
    notes: "4个浆果即可。纯粹的果实料理。",
    imagePath: "/images/foods/fist_full_of_jam.png",
  },
  {
    id: "fruit_medley",
    name: "水果拼盘", nameEn: "Fruit Medley",
    category: "health", stats: { health: 20, hunger: 25, sanity: 5 },
    cookTime: 10, priority: 0, weight: 1,
    requirements: { minTags: { fruit: 3.0 } },
    minMeat: 0, maxMeat: 0,
    forbidsTags: ["meat", "inedible"],
    notes: "需要3个以上的水果值。3石榴+1浆果即可，回血不错。",
    imagePath: "/images/foods/fruit_medley.png",
  },
  {
    id: "stuffed_eggplant",
    name: "酿茄子", nameEn: "Stuffed Eggplant",
    category: "health", stats: { health: 3, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 1, weight: 1,
    requirements: { minTags: { vegetable: 0.5 } },
    requiresSpecific: ["eggplant"],
    notes: "需要茄子+蔬菜。1茄子+1胡萝卜+2浆果即可。",
    imagePath: "/images/foods/stuffed_eggplant.png",
  },
  {
    id: "waffles",
    name: "华夫饼", nameEn: "Waffles",
    category: "health", stats: { health: 60, hunger: 37.5, sanity: 5 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: { minTags: { egg: 1.0 } },
    requiresSpecific: ["butter"],
    requiresTags: ["sweetener"],
    notes: "需要黄油+蛋+蜂蜜+浆果。1黄油+1蛋+1蜂蜜+1浆果。回血60！",
    imagePath: "/images/foods/waffles.png",
  },
  {
    id: "mandrake_soup",
    name: "曼德拉汤", nameEn: "Mandrake Soup",
    category: "health", stats: { health: 100, hunger: 150, sanity: 5 },
    cookTime: 60, priority: 10, weight: 1,
    requirements: {},
    requiresSpecific: ["mandrake"],
    notes: "需要曼德拉草。1曼德拉+3树枝即可。回血100+饱食150！但曼德拉全游戏只有几个。",
    imagePath: "/images/foods/mandrake_soup.png",
  },
  {
    id: "guacamole",
    name: "鼹鼠沙拉", nameEn: "Guacamole",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 0 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: {},
    requiresSpecific: ["mole"],
    requiresTags: ["fruit"],
    notes: "需要鼹鼠+水果。1鼹鼠+1浆果+2树枝即可。",
    imagePath: "/images/foods/guacamole.png",
  },
  {
    id: "creamy_potato_puree",
    name: "奶油土豆泥", nameEn: "Creamy Potato Purée",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 33 },
    cookTime: 20, priority: 20, weight: 1,
    requirements: {},
    requiresSpecific: ["potato"],
    requiresTags: ["dairy", "sweetener"],
    forbidsTags: ["meat"],
    notes: "需要土豆+大蒜/洋葱+乳制品+甜味剂。回理智33的素食。",
    imagePath: "/images/foods/creamy_potato_puree.png",
  },
  {
    id: "asparagus_soup",
    name: "芦笋汤", nameEn: "Asparagus Soup",
    category: "health", stats: { health: 20, hunger: 18.75, sanity: 5 },
    cookTime: 10, priority: 10, weight: 1,
    requirements: { minTags: { vegetable: 2.0 } },
    requiresSpecific: ["asparagus"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要芦笋+2蔬菜。1芦笋+2胡萝卜+1浆果即可。",
    imagePath: "/images/foods/asparagus_soup.png",
  },
  {
    id: "fancy_spiralled_tubers",
    name: "花式薯条", nameEn: "Fancy Spiralled Tubers",
    category: "health", stats: { health: 3, hunger: 37.5, sanity: 15 },
    cookTime: 15, priority: 10, weight: 1,
    requirements: {},
    requiresSpecific: ["potato"],
    requiresTags: ["inedible"],
    forbidsTags: ["meat"],
    notes: "需要土豆+树枝。1土豆+1树枝+2浆果即可。简单回理智。",
    imagePath: "/images/foods/fancy_spiralled_tubers.png",
  },
  {
    id: "salsa_fresca",
    name: "新鲜沙拉", nameEn: "Salsa Fresca",
    category: "health", stats: { health: 3, hunger: 25, sanity: 33 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: {},
    requiresSpecific: ["tomato"],
    requiresTags: ["vegetable", "fruit"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要番茄+洋葱/大蒜+水果+蔬菜。回理智33素食。",
    imagePath: "/images/foods/salsa_fresca.png",
  },
  // ==================== SEAFOOD RECIPES ====================
  {
    id: "lobster_bisque",
    name: "龙虾汤", nameEn: "Lobster Bisque",
    category: "health", stats: { health: 60, hunger: 25, sanity: 10 },
    cookTime: 10, priority: 30, weight: 1,
    requirements: { minTags: { fish: 1.0 } },
    requiresSpecific: ["wobster"],
    requiresTags: ["filler"],
    notes: "需要龙虾+冰+树枝。烤龙虾+1冰+2树枝。回血60！",
    imagePath: "/images/foods/lobster_bisque.png",
  },
  {
    id: "lobster_dinner",
    name: "龙虾大餐", nameEn: "Lobster Dinner",
    category: "health", stats: { health: 60, hunger: 37.5, sanity: 50 },
    cookTime: 10, priority: 30, weight: 1,
    requirements: { minTags: { fish: 1.0 } },
    requiresSpecific: ["wobster"],
    requiresTags: ["dairy"],
    forbidsTags: ["meat"],
    notes: "需要龙虾+黄油+树枝。1龙虾+1黄油+2树枝。回血60+理智50！",
    imagePath: "/images/foods/lobster_dinner.png",
  },
  {
    id: "seafood_gumbo",
    name: "海鲜浓汤", nameEn: "Seafood Gumbo",
    category: "health", stats: { health: 40, hunger: 37.5, sanity: 20 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fish: 2.0 } },
    requiresTags: ["inedible"],
    notes: "需要2鱼+树枝。2鱼+1树枝+1浆果即可。回40血+20理智。",
    imagePath: "/images/foods/seafood_gumbo.png",
  },
  {
    id: "moqueca",
    name: "莫奎卡", nameEn: "Moqueca",
    category: "health", stats: { health: 60, hunger: 37.5, sanity: 33 },
    cookTime: 40, priority: 30, weight: 1,
    requirements: { minTags: { fish: 1.0, vegetable: 1.0 } },
    requiresSpecific: ["tomato", "onion"],
    forbidsTags: ["inedible", "meat"],
    notes: "需要鱼+番茄+洋葱+蔬菜/水果。回血60+理智33的顶级鱼料理！",
    imagePath: "/images/foods/moqueca.png",
  },
  {
    id: "fish_cordon_bleu",
    name: "鱼排卷", nameEn: "Fish Cordon Bleu",
    category: "health", stats: { health: 20, hunger: 25, sanity: 0 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fish: 1.0 } },
    requiresSpecific: ["frog_legs"],
    forbidsTags: ["inedible"],
    notes: "需要鱼+蛙腿+树枝+蔬菜。",
    imagePath: "/images/foods/fish_cordon_bleu.png",
  },
  {
    id: "ceviche",
    name: "酸橘汁腌鱼", nameEn: "Ceviche",
    category: "health", stats: { health: 20, hunger: 25, sanity: 5 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fish: 1.0, vegetable: 1.0 } },
    requiresTags: ["filler"],
    forbidsTags: ["inedible"],
    notes: "需要鱼+蔬菜+冰。1鱼+1蔬菜+2冰即可。",
    imagePath: "/images/foods/ceviche.png",
  },
  {
    id: "california_roll",
    name: "加州卷", nameEn: "California Roll",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 10 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fish: 1.0 } },
    requiresSpecific: ["kelp"],
    requiresTags: ["inedible"],
    notes: "需要海带+鱼+树枝。1海带+1鱼+1树枝+1浆果。",
    imagePath: "/images/foods/california_roll.png",
  },
  {
    id: "unagi",
    name: "鳗鱼寿司", nameEn: "Unagi",
    category: "health", stats: { health: 20, hunger: 18.75, sanity: 5 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: {},
    requiresSpecific: ["eel"],
    requiresTags: ["inedible"],
    notes: "需要鳗鱼+树枝。1鳗鱼+1树枝+2浆果即可。",
    imagePath: "/images/foods/unagi.png",
  },
  // ==================== FIG RECIPES ====================
  {
    id: "figatoni",
    name: "无花果意面", nameEn: "Figatoni",
    category: "health", stats: { health: 30, hunger: 56.25, sanity: 15 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { vegetable: 0.5, dairy: 0.5 } },
    requiresSpecific: ["fig"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要无花果+蔬菜+乳制品。1无花果+1蔬菜+1电羊奶+1浆果。",
    imagePath: "/images/foods/figatoni.png",
  },
  {
    id: "fig_stuffed_trunk",
    name: "无花果酿象拔", nameEn: "Fig-Stuffed Trunk",
    category: "health", stats: { health: 60, hunger: 56.25, sanity: 10 },
    cookTime: 40, priority: 30, weight: 1,
    requirements: { minTags: { vegetable: 2.0 } },
    requiresSpecific: ["trunk", "fig"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要象鼻+无花果+2蔬菜。回血60的素食！",
    imagePath: "/images/foods/fig_stuffed_trunk.png",
  },
  {
    id: "figgy_frogwich",
    name: "无花果蛙腿三明治", nameEn: "Figgy Frogwich",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { vegetable: 0.5 } },
    requiresSpecific: ["frog_legs", "fig"],
    forbidsTags: ["inedible"],
    notes: "需要蛙腿+无花果+蔬菜。1蛙腿+1无花果+1蔬菜+1浆果。",
    imagePath: "/images/foods/figgy_frogwich.png",
  },
  {
    id: "figkabob",
    name: "无花果串", nameEn: "Figkabob",
    category: "health", stats: { health: 20, hunger: 25, sanity: 15 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { meat: 0.5 } },
    requiresSpecific: ["fig"],
    requiresTags: ["inedible"],
    notes: "需要无花果+肉+树枝。1无花果+1怪物肉+1树枝+1浆果。",
    imagePath: "/images/foods/figkabob.png",
  },
  // ==================== VOLT GOAT / SPECIAL ====================
  {
    id: "volt_goat_jelly",
    name: "电羊果冻", nameEn: "Volt Goat Jelly",
    category: "utility", stats: { health: 3, hunger: 37.5, sanity: 10 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { sweetener: 1.0 } },
    requiresSpecific: ["volt_goat_horn"],
    forbidsTags: ["inedible"],
    notes: "需要电羊角+蜂蜜+浆果。1电羊角+1蜂蜜+2浆果。给攻击附加电击伤害！",
    imagePath: "/images/foods/volt_goat_jelly.png",
  },
  {
    id: "volt_goat_chaud_froid",
    name: "电羊冻", nameEn: "Volt Goat Chaud-Froid",
    category: "utility", stats: { health: 3, hunger: 37.5, sanity: 10 },
    cookTime: 40, priority: 25, weight: 1,
    requirements: { minTags: { sweetener: 1.0, dairy: 0.5 } },
    requiresSpecific: ["volt_goat_horn"],
    forbidsTags: ["inedible", "meat"],
    notes: "需要电羊角+蜂蜜+乳制品。攻击附加电击+潮湿伤害！",
    imagePath: "/images/foods/volt_goat_chaud_froid.png",
  },
  {
    id: "bone_bouillon",
    name: "骨汤", nameEn: "Bone Bouillon",
    category: "utility", stats: { health: 3, hunger: 150, sanity: 0 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { meat: 2.0 } },
    requiresSpecific: ["bone_shards"],
    forbidsTags: ["inedible"],
    notes: "需要骨片+肉+蔬菜。1骨片+2大肉+1蔬菜。饱食150但减理智。",
    imagePath: "/images/foods/bone_bouillon.png",
  },
  {
    id: "hot_dragon_chili_salad",
    name: "火龙辣椒沙拉", nameEn: "Hot Dragon Chili Salad",
    category: "utility", stats: { health: 3, hunger: 25, sanity: 10 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { vegetable: 1.0, fruit: 0.5 } },
    requiresSpecific: ["dragon_fruit"],
    requiresTags: ["vegetable", "fruit"],
    notes: "需要火龙果+辣椒+蔬菜+水果。提升饱食度恢复+体温！",
    imagePath: "/images/foods/hot_dragon_chili_salad.png",
  },
  {
    id: "glow_berry_mousse",
    name: "发光浆果慕斯", nameEn: "Glow Berry Mousse",
    category: "utility", stats: { health: 3, hunger: 37.5, sanity: 10 },
    cookTime: 20, priority: 20, weight: 1,
    requirements: { minTags: { fruit: 1.0, sweetener: 0.5 } },
    requiresSpecific: ["glow_berry"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要发光浆果+蜂蜜+水果。吃了后会发光！洞穴探索神器。",
    imagePath: "/images/foods/glow_berry_mousse.png",
  },
  {
    id: "tall_scotch_eggs",
    name: "苏格兰蛋", nameEn: "Tall Scotch Eggs",
    category: "health", stats: { health: 60, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 25, weight: 1,
    requirements: { minTags: { egg: 4.0, vegetable: 1.0 } },
    forbidsTags: ["inedible"],
    notes: "需要高脚鸟蛋+蔬菜。1高脚鸟蛋+1蔬菜+2浆果。回血60！",
    imagePath: "/images/foods/tall_scotch_eggs.png",
  },
  {
    id: "breakfast_skillet",
    name: "早餐煎锅", nameEn: "Breakfast Skillet",
    category: "health", stats: { health: 3, hunger: 37.5, sanity: 5 },
    cookTime: 20, priority: 10, weight: 1,
    requirements: { minTags: { egg: 1.5, meat: 0.5, vegetable: 1.5 } },
    forbidsTags: ["dairy", "inedible"],
    notes: "需要蛋+肉+蔬菜的经典早餐组合。1蛋+1肉+1蔬菜+1蛋即可。",
    imagePath: "/images/foods/breakfast_skillet.png",
  },
  {
    id: "plain_omelette",
    name: "普通煎蛋", nameEn: "Plain Omelette",
    category: "health", stats: { health: 3, hunger: 37.5, sanity: 5 },
    cookTime: 10, priority: 5, weight: 1,
    requirements: { minTags: { egg: 3.0 } },
    minMeat: 0, maxMeat: 0,
    forbidsTags: ["meat", "inedible"],
    notes: "需要3个蛋。3蛋+1树枝即可。蛋多用不完时做这个。",
    imagePath: "/images/foods/plain_omelette.png",
  },
  // ==================== BARREL RECIPES（藤壶系列） ====================
  {
    id: "barnacle_nigiri",
    name: "藤壶寿司", nameEn: "Barnacle Nigiri",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 10, priority: 20, weight: 1,
    requirements: { minTags: { fish: 0.5 } },
    requiresSpecific: ["barnacle"],
    notes: "需要藤壶+鱼+树枝。1藤壶+1鱼+1树枝+1浆果。",
    imagePath: "/images/foods/barnacle_nigiri.png",
  },
  {
    id: "barnacle_linguini",
    name: "藤壶意面", nameEn: "Barnacle Linguini",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 15 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { vegetable: 2.0 } },
    requiresSpecific: ["barnacle"],
    forbidsTags: ["meat", "inedible"],
    notes: "需要藤壶+2蔬菜。1藤壶+2胡萝卜+1浆果即可。",
    imagePath: "/images/foods/barnacle_linguini.png",
  },
  {
    id: "barnacle_pita",
    name: "藤壶皮塔饼", nameEn: "Barnacle Pita",
    category: "health", stats: { health: 20, hunger: 37.5, sanity: 5 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { vegetable: 0.5, egg: 0.5 } },
    requiresSpecific: ["barnacle"],
    forbidsTags: ["inedible"],
    notes: "需要藤壶+蔬菜+蛋。1藤壶+1蔬菜+1蛋+1浆果。",
    imagePath: "/images/foods/barnacle_pita.png",
  },
  // ==================== GRIM/GRAVY ====================
  {
    id: "grim_galette",
    name: "恐怖薄饼", nameEn: "Grim Galette",
    category: "utility", stats: { health: 0, hunger: 25, sanity: 10 },
    cookTime: 40, priority: 20, weight: 1,
    requirements: { minTags: { sweetener: 2.0, egg: 0.5 } },
    requiresSpecific: ["nightmare_fuel"],
    forbidsTags: ["inedible"],
    notes: "需要梦魇燃料+2蜂蜜+蛋。特殊效果：交换生命值和理智值！",
    imagePath: "/images/foods/grim_galette.png",
  },
  // ==================== FAILURE RECIPES ====================
  {
    id: "wet_goop",
    name: "湿漉漉的垃圾", nameEn: "Wet Goop",
    category: "failure", stats: { health: 0, hunger: 0, sanity: 0 },
    cookTime: 10, priority: -2, weight: 1,
    requirements: {},
    notes: "没有任何食谱匹配时的默认结果。完全没用。",
    imagePath: "/images/foods/wet_goop.png",
  },
  {
    id: "monster_lasagna",
    name: "怪物千层面", nameEn: "Monster Lasagna",
    category: "failure", stats: { health: -20, hunger: 37.5, sanity: -20 },
    cookTime: 60, priority: 10, weight: 1,
    requirements: { minTags: { monster: 2.0 } },
    notes: "怪物肉太多（2个以上）时的结果。减血减理智。",
    imagePath: "/images/foods/monster_lasagna.png",
  },
];
